#!/usr/bin/env python3
"""
front/server.py — small read-only JSON backend for the Mastercard divergence
dashboard (front/TASKS.md, step 1).

Reuses mc_divergence's existing functions directly instead of duplicating any
fetch/parse/diff logic:
  - phase1_historical_audit.load_spec / audit_predig_vs_data_direct for the
    5 priority APIs' current status (pre-dig.yaml vs data.yaml, the same
    direct structural check the CLI report already leads with)
  - phase2_job_a_new_release_alert.get_release_notes_table / fetch_note_text /
    find_matching_apis + parse_release_note.parse_note for the latest release
  - fetch_mc_source.DEFAULT_CACHE_DIR for cache paths

Deliberately read-only for now (step 1): no route re-fetches from Mastercard
or re-runs the full note-based audit — it reads whatever's already cached
locally (same cache the CLI scripts already populate). Actions that trigger a
real run (Phase 1 audit, Phase 2 check) are step 4 in TASKS.md, not this one.

Usage:
    pip install flask
    python3 front/server.py
    -> http://127.0.0.1:5000/api/phase1
    -> http://127.0.0.1:5000/api/phase2/latest
    -> http://127.0.0.1:5000/api/reports
"""

import json
import os
import sys

from flask import Flask, jsonify, request, send_from_directory

MC_DIVERGENCE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, "mc_divergence")
MC_DIVERGENCE_DIR = os.path.normpath(MC_DIVERGENCE_DIR)
sys.path.insert(0, MC_DIVERGENCE_DIR)

PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))
sys.path.insert(0, PROJECT_ROOT)

import fetch_mc_source
import mdes_cs_divergence_report
import send_email as send_email_module
import phase1_historical_audit
from phase1_historical_audit import (
    DEFAULT_DATA_YAML, PRIORITY_PATH_DISPLAY, audit_predig_vs_data_direct, load_spec,
    group_shared_schema_fixes, summarize_by_data_target, summarize_schema_fix_clusters,
)
import phase2_job_a_new_release_alert
from phase2_job_a_new_release_alert import TARGET_APIS, fetch_note_text, find_matching_apis, get_release_notes_table
from parse_release_note import parse_note

FRONT_DIR = os.path.dirname(os.path.abspath(__file__))
app = Flask(__name__, static_folder=FRONT_DIR, static_url_path="")

# MDES Customer Service API -> Java field mapping, generated by
# extract_java_field_mapping.py in the pwc-api-sp5_api checkout (see
# MDES_CS_API_JAVA_MAPPING_LINK.md). Linked by path, same convention as
# DEFAULT_DATA_YAML -- not vendored into this repo.
MDES_CS_MAPPING_JSON = os.environ.get(
    'MDES_CS_MAPPING_JSON',
    r'C:\Users\moham\Downloads\pwc-api-sp5_api\Mdes_cs_api\generated\mdes_cs_api_schemas.generated.json',
)


@app.get("/")
def index():
    return send_from_directory(FRONT_DIR, "index.html")

CACHE_DIR = fetch_mc_source.DEFAULT_CACHE_DIR
REPORTS_DIR = os.path.join(MC_DIVERGENCE_DIR, "reports")


# ============================================================================
# 1. GET /api/phase1 — 5 priority APIs, current status
# ============================================================================

def compute_phase1_priority_status():
    """Direct pre-dig.yaml vs data.yaml diff on the 5 priority endpoints —
    same check phase1_historical_audit.py's CLI report leads with, reused
    as-is. Reads whatever's already cached; does NOT hit the network (that's
    what running the real phase1_historical_audit.py script does)."""
    predig_path = os.path.join(CACHE_DIR, "pre-dig.yaml")
    if not os.path.exists(predig_path):
        return None
    data_spec = load_spec(DEFAULT_DATA_YAML, repair=True)
    predig_spec = load_spec(predig_path, repair=True)
    return audit_predig_vs_data_direct(predig_spec, data_spec)


def summarize_api_status(entry):
    """entry = one value from audit_predig_vs_data_direct()'s result dict.
    Collapses its field-level results into one overall status for a
    dashboard tile: worst of {non_implemente, partiel, implemente}, counting
    only 'reliable' mismatches (see phase1_historical_audit.py's
    MINOR_NOISE_ATTRS — minLength/required noise from data.yaml's generation
    style is excluded, same as the CLI report already does)."""
    if not entry.get("endpoint_exists_in_predig"):
        return {"status": "unknown", "reliable_issues": 0, "total_fields": 0}
    if not entry["endpoint_exists_in_data"]:
        return {"status": "non_implemente", "reliable_issues": len(entry["fields"]), "total_fields": len(entry["fields"])}

    reliable_problems = [f for f in entry["fields"] if f["status"] != "implemente" and f["reliable"]]
    if any(f["status"] == "non_implemente" for f in reliable_problems):
        status = "non_implemente"
    elif reliable_problems:
        status = "partiel"
    else:
        status = "implemente"
    return {"status": status, "reliable_issues": len(reliable_problems), "total_fields": len(entry["fields"])}


@app.get("/api/phase1")
def api_phase1():
    predig_direct = compute_phase1_priority_status()
    if predig_direct is None:
        return jsonify({
            "error": "cache/pre-dig.yaml not found — run phase1_historical_audit.py "
                     "(or fetch_mc_source.py) at least once first.",
        }), 503

    apis = []
    for path, display in PRIORITY_PATH_DISPLAY:
        entry = predig_direct[path]
        summary = summarize_api_status(entry)
        apis.append({
            "path": path,
            "display": display,
            **summary,
            "fields": entry["fields"],
        })

    field_clusters = group_shared_schema_fixes(predig_direct)
    shared_fixes = [{
        **target,
        "schemas": [p for p in summarize_schema_fix_clusters(field_clusters) if p["data_origin"] == target["data_origin"]],
    } for target in summarize_by_data_target(field_clusters)]

    return jsonify({"apis": apis, "shared_fixes": shared_fixes})


# ============================================================================
# 2. GET /api/phase2/latest — latest release in the index, checked against
#    the 5 tracked APIs
# ============================================================================

@app.get("/api/phase2/latest")
def api_phase2_latest():
    entries = get_release_notes_table(CACHE_DIR, refresh=False)
    if not entries:
        return jsonify({"error": "cache/known_releases.json not found or empty — run "
                                  "fetch_mc_source.py at least once first."}), 503

    entry = entries[0]
    text = fetch_note_text(entry, CACHE_DIR)
    matched_apis = find_matching_apis(text)
    parsed = parse_note(text, url=entry["url"]) if matched_apis else None

    return jsonify({
        "title": entry["title"],
        "url": entry["url"],
        "mdes_release": entry["mdes_release"],
        "note_type": entry["note_type"],
        "upgrade_date": entry["upgrade_date"],
        "tracked_apis": TARGET_APIS,
        "matched_apis": matched_apis,
        "parsed": parsed,
    })


# ============================================================================
# 3. GET /api/reports — list of already-generated report/email files
# ============================================================================

@app.get("/api/reports")
def api_reports():
    if not os.path.isdir(REPORTS_DIR):
        return jsonify({"reports": []})

    reports = []
    for name in os.listdir(REPORTS_DIR):
        path = os.path.join(REPORTS_DIR, name)
        if not os.path.isfile(path):
            continue
        stat = os.stat(path)
        reports.append({
            "name": name,
            "size_bytes": stat.st_size,
            "modified_at": stat.st_mtime,
        })
    reports.sort(key=lambda r: r["modified_at"], reverse=True)
    return jsonify({"reports": reports})


@app.get("/reports/<path:name>")
def get_report_file(name):
    """Raw report file. send_from_directory uses Werkzeug's safe_join under
    the hood, so a name containing '..' can't escape REPORTS_DIR. Mimetype is
    guessed from the extension (.xlsx vs .md) instead of being hardcoded, so
    the Excel reports open correctly instead of downloading as plain text."""
    return send_from_directory(REPORTS_DIR, name)


# ============================================================================
# 3b. GET /api/mdes_cs_mapping — MDES Customer Service API -> Java field
#     mapping (generated externally, read-only here, see MDES_CS_MAPPING_JSON)
# ============================================================================

@app.get("/api/mdes_cs_mapping")
def api_mdes_cs_mapping():
    if not os.path.exists(MDES_CS_MAPPING_JSON):
        return jsonify({
            "error": f"Fichier introuvable : {MDES_CS_MAPPING_JSON} — régénérer avec "
                     "extract_java_field_mapping.py (voir MDES_CS_API_JAVA_MAPPING_LINK.md).",
        }), 503

    with open(MDES_CS_MAPPING_JSON, encoding="utf-8") as f:
        raw = json.load(f)

    operations = []
    for op in raw.get("operations", []):
        variants = []
        total_fields = 0
        unresolved_count = 0
        for variant_name, variant in op.get("variants", {}).items():
            fields = []
            flat_fields = mdes_cs_divergence_report.flatten_java_fields(variant.get("fields", {}))
            for field_path, info in flat_fields.items():
                fields.append({
                    "path": field_path,
                    "type": info.get("type"),
                    "source": info.get("source"),
                    "java_source": info.get("javaSource"),
                    "java_expr": info.get("javaExpr"),
                })
                total_fields += 1
                if info.get("source") == "unresolved":
                    unresolved_count += 1
            variants.append({
                "name": variant_name,
                "builder_method": variant.get("builderMethod"),
                "source_lines": variant.get("sourceLines"),
                "fields": fields,
            })
        operations.append({
            "operation": op.get("operation"),
            "path": op.get("path"),
            "internal_path": op.get("internalPath"),
            "java_file": op.get("javaFile"),
            "total_fields": total_fields,
            "unresolved_count": unresolved_count,
            "variants": variants,
        })

    return jsonify({
        "generated_at": raw.get("_meta", {}).get("generatedAt"),
        "source_tag_legend": raw.get("_meta", {}).get("sourceTagLegend", {}),
        "operations": operations,
    })


# ============================================================================
# 3c. GET /api/mdes_cs_divergence — official MDES CS spec vs what the Java
#     codebase actually builds (see mdes_cs_divergence_report.py). Same
#     relationship as /api/phase1, applied to the CS API domain.
# ============================================================================

@app.get("/api/mdes_cs_divergence")
def api_mdes_cs_divergence():
    if not os.path.exists(mdes_cs_divergence_report.DEFAULT_CS_SPEC_YAML):
        return jsonify({
            "error": f"Spec introuvable : {mdes_cs_divergence_report.DEFAULT_CS_SPEC_YAML}",
        }), 503
    if not os.path.exists(mdes_cs_divergence_report.DEFAULT_CS_JAVA_MAPPING_JSON):
        return jsonify({
            "error": f"Mapping Java introuvable : {mdes_cs_divergence_report.DEFAULT_CS_JAVA_MAPPING_JSON}",
        }), 503

    report = mdes_cs_divergence_report.run(
        mdes_cs_divergence_report.DEFAULT_CS_SPEC_YAML,
        mdes_cs_divergence_report.DEFAULT_CS_JAVA_MAPPING_JSON,
    )
    return jsonify(report)


# ============================================================================
# 4. Actions — actually re-run a script, not just read the cache
#    (front/TASKS.md, step 4). Synchronous: the request blocks until the run
#    finishes, same as calling the CLI script directly — fine for a small
#    internal tool, no background job queue needed.
# ============================================================================

def _run_phase2_check(check_result, extra_fields=None):
    """Shared response-building tail for both phase2 check routes: writes
    the Excel report (one sheet per impacted tracked API) when 2+ releases
    impact tracked APIs, and shapes the JSON payload the front-end's outcome
    popup/email-preview flow expects. No .md file is written anywhere.
    NEVER sends — sending only happens from /api/phase2/send, after the
    user has reviewed (and optionally edited) the subject/body in the
    front-end popup."""
    relevant = check_result["relevant"]
    result = {
        "outcome": check_result["outcome"],
        "checked_count": len(check_result["working_set"]),
        "checked_titles": [e["title"] for e in check_result["working_set"]],
        "relevant": bool(relevant),
        **(extra_fields or {}),
    }

    if not relevant:
        return jsonify(result)

    matched_apis = sorted({api for r in relevant for api in r["matched_apis"]},
                           key=phase2_job_a_new_release_alert.TARGET_APIS.index)
    subject = phase2_job_a_new_release_alert.email_subject(relevant)
    body = phase2_job_a_new_release_alert.render_email_body(relevant)

    xlsx_path = phase2_job_a_new_release_alert.default_report_xlsx_path()
    os.makedirs(os.path.dirname(xlsx_path), exist_ok=True)
    phase2_job_a_new_release_alert.render_report_xlsx(relevant, xlsx_path)

    result.update({
        "report_path": xlsx_path,
        "matched_apis": matched_apis,
        "relevant_titles": [r["title"] for r in relevant],
        "subject": subject,
        "body": body,
    })
    return jsonify(result)


@app.post("/api/phase2/check-pending")
def api_phase2_check_pending():
    """'Vérifier après le dernier pre-dig' button: every release not yet
    reflected in pre-dig.yaml (Production date still in the future),
    recomputed fresh every call — independent of the checkpoint. The ONLY
    action that ADVANCES cache/phase2_checkpoint.json afterward (regardless
    of outcome) — the authoritative sweep that moves the reference point
    the other button (check-latest) compares against."""
    entries = phase2_job_a_new_release_alert.get_release_notes_table(CACHE_DIR, refresh=True)
    if not entries:
        return jsonify({"error": "Aucune release trouvée dans l'index Mastercard."}), 502

    check = phase2_job_a_new_release_alert.check_pending_since_predig(entries, CACHE_DIR)
    phase2_job_a_new_release_alert.advance_checkpoint(CACHE_DIR, entries)
    return _run_phase2_check(check)


@app.post("/api/phase2/check-latest")
def api_phase2_check_latest():
    """'Vérifier la dernière release' button: releases newer than whatever
    check-pending last examined (the persisted checkpoint). Deliberately
    does NOT advance the checkpoint itself, so repeated clicks keep
    re-showing the same still-new release(s) until check-pending runs
    again. Falls back to just the single newest table entry if
    check-pending has never been run yet (no checkpoint)."""
    entries = phase2_job_a_new_release_alert.get_release_notes_table(CACHE_DIR, refresh=True)
    if not entries:
        return jsonify({"error": "Aucune release trouvée dans l'index Mastercard."}), 502

    check = phase2_job_a_new_release_alert.check_since_checkpoint(entries, CACHE_DIR)
    return _run_phase2_check(check, extra_fields={"used_fallback": check["used_fallback"]})


@app.post("/api/phase2/send")
def api_phase2_send():
    """Actually sends the email via send_email.py, using whatever subject/
    body the front-end popup submits — i.e. possibly edited by the user
    after reviewing what /api/phase2/run prepared. This is the ONLY route
    that sends for phase 2; /api/phase2/run never does."""
    payload = request.get_json(silent=True) or {}
    subject, body = payload.get("subject"), payload.get("body")
    if not subject or not body:
        return jsonify({"error": "Objet et corps requis."}), 400

    report_path = payload.get("report_path")
    attachments = [report_path] if report_path and os.path.exists(report_path) else None
    try:
        sent_to = send_email_module.send_email(subject, body, attachments=attachments)
    except send_email_module.SmtpConfigError as e:
        return jsonify({"error": str(e)}), 502

    return jsonify({"sent_to": sent_to})


@app.post("/api/phase1/run")
def api_phase1_run():
    """Re-runs phase1_historical_audit.py's actual run() end to end: fresh
    pre-dig.yaml, full note-based audit since 'cutoff', report + email draft
    written. Always called with send=False — sending only happens from
    /api/phase1/send, after the user reviews/edits the draft in the popup.
    Can take a while (fetches/parses every release note since the cutoff),
    the request blocks until it's done."""
    payload = request.get_json(silent=True) or {}
    cutoff_str = payload.get("cutoff", "2025-01")

    try:
        cutoff = phase1_historical_audit.parse_cutoff(cutoff_str)
    except (ValueError, AttributeError):
        return jsonify({"error": f"Cutoff invalide : '{cutoff_str}' (attendu YYYY-MM)"}), 400

    audited_notes, subject, body = phase1_historical_audit.run(
        DEFAULT_DATA_YAML, cutoff, CACHE_DIR,
        phase1_historical_audit.DEFAULT_REPORT_XLSX_PATH,
        refresh=True, send=False,
    )

    return jsonify({
        "cutoff": cutoff_str,
        "releases_audited": len(audited_notes),
        "report_path": phase1_historical_audit.DEFAULT_REPORT_XLSX_PATH,
        "subject": subject,
        "body": body,
    })


@app.post("/api/phase1/send")
def api_phase1_send():
    """Actually sends the Phase 1 email via send_email.py, with the
    (possibly user-edited) subject/body from the popup, attaching the full
    report — same as the CLI's --send does. Only sending route for phase 1."""
    payload = request.get_json(silent=True) or {}
    subject, body = payload.get("subject"), payload.get("body")
    if not subject or not body:
        return jsonify({"error": "Objet et corps requis."}), 400

    report_path = payload.get("report_path")
    attachments = [report_path] if report_path and os.path.exists(report_path) else None
    try:
        sent_to = send_email_module.send_email(subject, body, attachments=attachments)
    except send_email_module.SmtpConfigError as e:
        return jsonify({"error": str(e)}), 502

    return jsonify({"sent_to": sent_to})


if __name__ == "__main__":
    app.run(debug=True, use_reloader=False)
